[project]
name = "yt"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "pytubefix>=10.3.6",
]

[dependency-groups]
dev = [
    "basedpyright>=1.36.0",
    "ruff>=0.14.8",
]
